# Install packages for your first time using these packages
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("knitr")
install.packages("lubridate")
install.packages("ggpubr")
install.packages("mgcv")
install.packages("PerformanceAnalytics")
install.packages("fields")
install.packages("maps")
install.packages("mapdata")
install.packages("mapproj")
install.packages("dplyr")
